name: Deploy to GitHub Pages

on:
  # 수동 실행을 위한 워크플로우 디스패치 설정
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "Deploy Type"
        required: true
        default: "publish"
        type: choice
        options:
          - publish
          - unpublish
  # 자동 배포 (main 브랜치에 push 될 때)
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # unpublish가 선택되었을 때는 빌드 작업을 건너뜁니다
    if: github.event.inputs.deploy_type != 'unpublish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    if: github.event.inputs.deploy_type != 'unpublish'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  unpublish:
    if: github.event.inputs.deploy_type == 'unpublish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unpublish GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enable: false

      - name: Delete GitHub Pages branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git push origin --delete gh-pages || true
